name: "Publish to VS Marketplace"

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to branch
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Install packages
        run: npm ci

      - name: Calculate version
        id: calculateVersion
        run: |
          APP_VERSION=`cat package.json | jq ".version" -M | sed 's/\"//g'`
          echo "AppVersion=$APP_VERSION" >> $GITHUB_OUTPUT
          echo "app version = v$APP_VERSION"

      - name: Build VSIX package
        run: npm run build -- -o lazyarmadev-${{ steps.calculateVersion.outputs.AppVersion }}.vsix

    #   - name: Publish extension package
    #     run: npm run vsce -- publish -p ${{ secrets.VS_MARKETPLACE_TOKEN }}

      - name: Create tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: v${{ steps.calculateVersion.outputs.AppVersion }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ steps.calculateVersion.outputs.AppVersion }}
          artifacts: lazyarmadev-${{ steps.calculateVersion.outputs.AppVersion }}.vsix
          generateReleaseNotes: true