name: "Close stale issues and PRs"
on:
  schedule:
    # Format: minute hour day_of_month month day_of_week, everything is UTC
    # "*" = any
    - cron: "33 17 * * *"

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9